// <auto-generated />
using System;
using GymScan.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymScan.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526161800_AddFoodScanAndMealLog")]
    partial class AddFoodScanAndMealLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymScan.Database.Entities.Auth.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshSessions", "dbo");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double?>("HeightCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("float(5)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SetupStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("WeightKg")
                        .HasPrecision(5, 1)
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.DailyNutritionGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CaloriesTarget")
                        .HasColumnType("int");

                    b.Property<double>("CarbohydratesGramsTarget")
                        .HasPrecision(7, 1)
                        .HasColumnType("float(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("FatGramsTarget")
                        .HasPrecision(7, 1)
                        .HasColumnType("float(7)");

                    b.Property<string>("GoalSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("ProteinGramsTarget")
                        .HasPrecision(7, 1)
                        .HasColumnType("float(7)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive")
                        .IsUnique();

                    b.ToTable("DailyNutritionGoals", "dbo");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.FoodScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Calories")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ConfidencePercent")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Fat")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Protein")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ResultSource")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ServingSizeGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ScannedAt");

                    b.ToTable("FoodScans", "dbo");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.LocalFoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternateNames")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FatPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TypicalServingSizeGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("LocalFoodItems", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            AlternateNames = "koshari|كشري",
                            CaloriesPer100g = 160m,
                            CarbsPer100g = 28m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3m,
                            Name = "Koshary",
                            ProteinPer100g = 5.5m,
                            TypicalServingSizeGrams = 350m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            AlternateNames = "foul medames|فول مدمس",
                            CaloriesPer100g = 110m,
                            CarbsPer100g = 15m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2.5m,
                            Name = "Ful Medames",
                            ProteinPer100g = 7.5m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            AlternateNames = "falafel|طعمية",
                            CaloriesPer100g = 330m,
                            CarbsPer100g = 32m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 18m,
                            Name = "Ta'meya",
                            ProteinPer100g = 13m,
                            TypicalServingSizeGrams = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            AlternateNames = "حواوشي",
                            CaloriesPer100g = 280m,
                            CarbsPer100g = 22m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 15m,
                            Name = "Hawawshi",
                            ProteinPer100g = 14m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            AlternateNames = "mulukhiyah|ملوخية",
                            CaloriesPer100g = 30m,
                            CarbsPer100g = 3.5m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.4m,
                            Name = "Molokhia",
                            ProteinPer100g = 3m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            AlternateNames = "stuffed vegetables|محشي",
                            CaloriesPer100g = 120m,
                            CarbsPer100g = 16m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 5m,
                            Name = "Mahshi",
                            ProteinPer100g = 3.5m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            AlternateNames = "feteer|فطير مشلتت",
                            CaloriesPer100g = 360m,
                            CarbsPer100g = 38m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 20m,
                            Name = "Feteer Meshaltet",
                            ProteinPer100g = 6m,
                            TypicalServingSizeGrams = 150m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000008"),
                            AlternateNames = "kibda|كبدة اسكندراني",
                            CaloriesPer100g = 190m,
                            CarbsPer100g = 8m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 8m,
                            Name = "Liver Sandwich",
                            ProteinPer100g = 22m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000009"),
                            AlternateNames = "شاورما",
                            CaloriesPer100g = 215m,
                            CarbsPer100g = 12m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 11m,
                            Name = "Shawarma",
                            ProteinPer100g = 17m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000010"),
                            AlternateNames = "كفتة",
                            CaloriesPer100g = 260m,
                            CarbsPer100g = 5m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 19m,
                            Name = "Kofta",
                            ProteinPer100g = 18m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000011"),
                            AlternateNames = "فراخ مشوية",
                            CaloriesPer100g = 165m,
                            CarbsPer100g = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.6m,
                            Name = "Grilled Chicken",
                            ProteinPer100g = 31m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000012"),
                            AlternateNames = "رز مصري|vermicelli rice",
                            CaloriesPer100g = 180m,
                            CarbsPer100g = 35m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3m,
                            Name = "Egyptian Rice",
                            ProteinPer100g = 3.5m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000013"),
                            AlternateNames = "عيش بلدي|aish baladi",
                            CaloriesPer100g = 275m,
                            CarbsPer100g = 55m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 1.5m,
                            Name = "Baladi Bread",
                            ProteinPer100g = 9m,
                            TypicalServingSizeGrams = 90m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000014"),
                            AlternateNames = "شوربة عدس|ads soup",
                            CaloriesPer100g = 65m,
                            CarbsPer100g = 10m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.8m,
                            Name = "Lentil Soup",
                            ProteinPer100g = 4.5m,
                            TypicalServingSizeGrams = 350m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000015"),
                            AlternateNames = "بابا غنوج",
                            CaloriesPer100g = 120m,
                            CarbsPer100g = 8m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 9m,
                            Name = "Baba Ghanoush",
                            ProteinPer100g = 2.5m,
                            TypicalServingSizeGrams = 100m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000016"),
                            AlternateNames = "حمص",
                            CaloriesPer100g = 166m,
                            CarbsPer100g = 14m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 10m,
                            Name = "Hummus",
                            ProteinPer100g = 8m,
                            TypicalServingSizeGrams = 100m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000017"),
                            AlternateNames = "أم علي",
                            CaloriesPer100g = 250m,
                            CarbsPer100g = 30m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 12m,
                            Name = "Om Ali",
                            ProteinPer100g = 6m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000018"),
                            AlternateNames = "kunafa|كنافة",
                            CaloriesPer100g = 390m,
                            CarbsPer100g = 45m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 20m,
                            Name = "Konafa",
                            ProteinPer100g = 7m,
                            TypicalServingSizeGrams = 150m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000019"),
                            AlternateNames = "بسبوسة|namoura",
                            CaloriesPer100g = 340m,
                            CarbsPer100g = 50m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 14m,
                            Name = "Basbousa",
                            ProteinPer100g = 4m,
                            TypicalServingSizeGrams = 80m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000020"),
                            AlternateNames = "عيران|laban",
                            CaloriesPer100g = 40m,
                            CarbsPer100g = 4m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 1.5m,
                            Name = "Ayran",
                            ProteinPer100g = 2m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000021"),
                            AlternateNames = "hibiscus|كركديه",
                            CaloriesPer100g = 5m,
                            CarbsPer100g = 1m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0m,
                            Name = "Karkade",
                            ProteinPer100g = 0.1m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000022"),
                            AlternateNames = "فطير بلدي",
                            CaloriesPer100g = 310m,
                            CarbsPer100g = 40m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 13m,
                            Name = "Fiteer Baladi",
                            ProteinPer100g = 7m,
                            TypicalServingSizeGrams = 120m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000023"),
                            AlternateNames = "بصارة|fava bean dip",
                            CaloriesPer100g = 90m,
                            CarbsPer100g = 12m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2m,
                            Name = "Bessara",
                            ProteinPer100g = 6m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000024"),
                            AlternateNames = "مسقعة|eggplant moussaka",
                            CaloriesPer100g = 95m,
                            CarbsPer100g = 8m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 6m,
                            Name = "Moussaka",
                            ProteinPer100g = 3m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000025"),
                            AlternateNames = "okra stew|باميه",
                            CaloriesPer100g = 55m,
                            CarbsPer100g = 5m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2.5m,
                            Name = "Bamia",
                            ProteinPer100g = 4m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000026"),
                            AlternateNames = "فتة",
                            CaloriesPer100g = 200m,
                            CarbsPer100g = 20m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 9m,
                            Name = "Fattah",
                            ProteinPer100g = 10m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000027"),
                            AlternateNames = "كباب",
                            CaloriesPer100g = 245m,
                            CarbsPer100g = 3m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 17m,
                            Name = "Kebab",
                            ProteinPer100g = 20m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000028"),
                            AlternateNames = "rice pudding|رز بلبن",
                            CaloriesPer100g = 130m,
                            CarbsPer100g = 22m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3m,
                            Name = "Roz Bel Laban",
                            ProteinPer100g = 3.5m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000029"),
                            AlternateNames = "عدس أصفر|yellow lentils",
                            CaloriesPer100g = 116m,
                            CarbsPer100g = 20m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.4m,
                            Name = "Kushari Lentils",
                            ProteinPer100g = 9m,
                            TypicalServingSizeGrams = 150m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000030"),
                            AlternateNames = "فول بالزيت",
                            CaloriesPer100g = 140m,
                            CarbsPer100g = 14m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 6m,
                            Name = "Foul with Oil",
                            ProteinPer100g = 7m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000031"),
                            AlternateNames = "waraq enab|ورق عنب|dolma",
                            CaloriesPer100g = 130m,
                            CarbsPer100g = 17m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 5.5m,
                            Name = "Grape Leaves",
                            ProteinPer100g = 3m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000032"),
                            AlternateNames = "samosa|سمبوسك",
                            CaloriesPer100g = 310m,
                            CarbsPer100g = 28m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 18m,
                            Name = "Sambousek",
                            ProteinPer100g = 8m,
                            TypicalServingSizeGrams = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000033"),
                            AlternateNames = "شكشوكة",
                            CaloriesPer100g = 100m,
                            CarbsPer100g = 6m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 5.5m,
                            Name = "Shakshuka",
                            ProteinPer100g = 7m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000034"),
                            AlternateNames = "طحينة",
                            CaloriesPer100g = 595m,
                            CarbsPer100g = 21m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 54m,
                            Name = "Tahini",
                            ProteinPer100g = 17m,
                            TypicalServingSizeGrams = 30m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000035"),
                            AlternateNames = "دقة",
                            CaloriesPer100g = 480m,
                            CarbsPer100g = 20m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 38m,
                            Name = "Dukkah",
                            ProteinPer100g = 18m,
                            TypicalServingSizeGrams = 15m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000036"),
                            AlternateNames = "جبنة دمياطي|Egyptian white cheese",
                            CaloriesPer100g = 260m,
                            CarbsPer100g = 2m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 21m,
                            Name = "Gibna Domiati",
                            ProteinPer100g = 16m,
                            TypicalServingSizeGrams = 50m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000037"),
                            AlternateNames = "halva|حلاوة طحينية",
                            CaloriesPer100g = 500m,
                            CarbsPer100g = 55m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 27m,
                            Name = "Halawa Tahinia",
                            ProteinPer100g = 12m,
                            TypicalServingSizeGrams = 40m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000038"),
                            AlternateNames = "mixed vegetable stew|تورلي",
                            CaloriesPer100g = 60m,
                            CarbsPer100g = 8m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2.5m,
                            Name = "Torly",
                            ProteinPer100g = 2m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000039"),
                            AlternateNames = "baked pasta|مكرونة بشاميل",
                            CaloriesPer100g = 195m,
                            CarbsPer100g = 22m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 8.5m,
                            Name = "Macarona Bechamel",
                            ProteinPer100g = 8m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000040"),
                            AlternateNames = "فتة لحمة|meat fattah",
                            CaloriesPer100g = 210m,
                            CarbsPer100g = 18m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 10m,
                            Name = "Fatta",
                            ProteinPer100g = 12m,
                            TypicalServingSizeGrams = 350m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000041"),
                            AlternateNames = "cottage cheese|جبنة قريش",
                            CaloriesPer100g = 98m,
                            CarbsPer100g = 3.5m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 4.5m,
                            Name = "Gebna Areesh",
                            ProteinPer100g = 11m,
                            TypicalServingSizeGrams = 100m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000042"),
                            AlternateNames = "ساندوتش فول",
                            CaloriesPer100g = 200m,
                            CarbsPer100g = 28m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 6m,
                            Name = "Foul Sandwich",
                            ProteinPer100g = 8m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000043"),
                            AlternateNames = "مسقعة باذنجان|fried eggplant",
                            CaloriesPer100g = 100m,
                            CarbsPer100g = 7m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 7m,
                            Name = "Mesaka'a",
                            ProteinPer100g = 2.5m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000044"),
                            AlternateNames = "كباب حلة|pot kebab",
                            CaloriesPer100g = 150m,
                            CarbsPer100g = 6m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 8m,
                            Name = "Kabab Halla",
                            ProteinPer100g = 13m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000045"),
                            AlternateNames = "سحلب",
                            CaloriesPer100g = 90m,
                            CarbsPer100g = 16m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2m,
                            Name = "Sahlab",
                            ProteinPer100g = 2m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000046"),
                            AlternateNames = "كشري بالصلصة",
                            CaloriesPer100g = 170m,
                            CarbsPer100g = 30m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.5m,
                            Name = "Kushari with Sauce",
                            ProteinPer100g = 5.5m,
                            TypicalServingSizeGrams = 400m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000047"),
                            AlternateNames = "بانيه|breaded chicken",
                            CaloriesPer100g = 230m,
                            CarbsPer100g = 14m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 12m,
                            Name = "Chicken Pane",
                            ProteinPer100g = 18m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000048"),
                            AlternateNames = "كبدة اسكندراني",
                            CaloriesPer100g = 175m,
                            CarbsPer100g = 5m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 7m,
                            Name = "Alexandrian Liver",
                            ProteinPer100g = 23m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000049"),
                            AlternateNames = "ساندوتش سجق|sogo2",
                            CaloriesPer100g = 280m,
                            CarbsPer100g = 24m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 15m,
                            Name = "Sausage Sandwich",
                            ProteinPer100g = 12m,
                            TypicalServingSizeGrams = 200m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000050"),
                            AlternateNames = "ساندوتش طعمية",
                            CaloriesPer100g = 290m,
                            CarbsPer100g = 34m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 13m,
                            Name = "Taameya Sandwich",
                            ProteinPer100g = 10m,
                            TypicalServingSizeGrams = 180m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000051"),
                            AlternateNames = "فتة بالخل",
                            CaloriesPer100g = 180m,
                            CarbsPer100g = 22m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 6m,
                            Name = "Fatteh with Vinegar",
                            ProteinPer100g = 9m,
                            TypicalServingSizeGrams = 250m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000052"),
                            AlternateNames = "مشويات مشكلة",
                            CaloriesPer100g = 220m,
                            CarbsPer100g = 2m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 13m,
                            Name = "Mixed Grill",
                            ProteinPer100g = 24m,
                            TypicalServingSizeGrams = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000053"),
                            AlternateNames = "قطايف",
                            CaloriesPer100g = 300m,
                            CarbsPer100g = 40m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 13m,
                            Name = "Qatayef",
                            ProteinPer100g = 6m,
                            TypicalServingSizeGrams = 80m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000054"),
                            AlternateNames = "بيض بلدي|fried eggs",
                            CaloriesPer100g = 196m,
                            CarbsPer100g = 1m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 15m,
                            Name = "Baladi Eggs",
                            ProteinPer100g = 14m,
                            TypicalServingSizeGrams = 120m
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000055"),
                            AlternateNames = "مهلبية|milk pudding",
                            CaloriesPer100g = 110m,
                            CarbsPer100g = 18m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3m,
                            Name = "Mehalabeya",
                            ProteinPer100g = 3m,
                            TypicalServingSizeGrams = 200m
                        });
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Calories")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DiaryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Fat")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("FoodScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LocalFoodItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<decimal>("Protein")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ServingSizeGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodScanId");

                    b.HasIndex("LocalFoodItemId");

                    b.HasIndex("UserId", "DiaryDate");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("MealLogs", "dbo");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Auth.RefreshSession", b =>
                {
                    b.HasOne("GymScan.Database.Entities.Auth.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.DailyNutritionGoal", b =>
                {
                    b.HasOne("GymScan.Database.Entities.Auth.User", "User")
                        .WithOne("ActiveDailyNutritionGoal")
                        .HasForeignKey("GymScan.Database.Entities.Nutrition.DailyNutritionGoal", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.FoodScan", b =>
                {
                    b.HasOne("GymScan.Database.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Nutrition.MealLog", b =>
                {
                    b.HasOne("GymScan.Database.Entities.Nutrition.FoodScan", "FoodScan")
                        .WithMany()
                        .HasForeignKey("FoodScanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GymScan.Database.Entities.Nutrition.LocalFoodItem", "LocalFoodItem")
                        .WithMany()
                        .HasForeignKey("LocalFoodItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GymScan.Database.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodScan");

                    b.Navigation("LocalFoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymScan.Database.Entities.Auth.User", b =>
                {
                    b.Navigation("ActiveDailyNutritionGoal");

                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
